apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: reqnest
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root123
  DB_PASS: root123
  REDIS_PASSWORD: redis123
  REDIS_USER: default
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: reqnest
type: Opaque
stringData:
  # === OAuth Credentials ===
  GOOGLE_CLIENT_ID: 
  GOOGLE_CLIENT_SECRET: 

  # === JWT ===
  JWT_SECRET: supersecretjwtkey

  # === Mail Credentials ===
  MAIL_USERNAME: 
  MAIL_PASSWORD: 
  
  # === Razorpay ===
  RAZORPAY_KEY: 
  RAZORPAY_SECRET: 
